### ISSUE TITLE
Why the difference between two versions？

### ISSUE THREAD

**Issue by ThaliaHuang** [ncsoft/PhonMatchNet#11]
Hello, I would like to ask if there is any special purpose for the different architectures in TensorFlow and PyTorch versions as shown in PMNet_torch_figure.png?

**Comment by LeeYongHyeok** [comment]
Hi @ThaliaHuang, We intended our model to support both TensorFlow and PyTorch. However, since we used a pre-trained audio embedder distributed as a TFLite model, using it directly in PyTorch was challenging. Therefore, in the PyTorch version, we modified the implementation so that the output of the pre-trained embedder would be saved separately and utilized during training. If you aim for complete reproducibility of our paper, we recommend using the TensorFlow version.
