### ISSUE TITLE
Could you provide pre-trained weights?

### ISSUE THREAD

**Issue by jeanlaroche** [ncsoft/PhonMatchNet#12]
I would love to test your code, would it be possible for you to share your pre-trained weights?

**Comment by LeeYongHyeok** [comment]
Hi @jeanlaroche, 
Unfortunately, due to our organization's policy regarding the disclosure of research, we are unable to provide the pre-trained model. Instead, we have released the code in both TensorFlow and PyTorch to ensure reproducibility of our research. We encourage you to utilize this code for training.
