### ISSUE TITLE
Releasing the baseline codebase

### ISSUE THREAD

**Issue by coding-dallas** [ncsoft/PhonMatchNet#4]
Hi,
In the paper you mentioned that you reproduced the baseline paper. Is it possible to release that code also publicly.

**Comment by LeeYongHyeok** [comment]
Hi, @coding-dallas,

Thank you very much for your significant interest in our paper. While we did not explicitly specify a baseline model, adjusting the hyperparameters of our UKWS model may likely allow you to generate it. We apologize for not providing precise code as it has been quite some time since we conducted these reproducibility experiments, and we haven't had the opportunity to organize the relevant content.

**Comment by coding-dallas** [comment]
The baseline I was referring to CMCD approach (Learning Audio-Text Agreement for Open-vocabulary Keyword Spotting). Can you release this code.

**Comment by LeeYongHyeok** [comment]
@coding-dallas,
Yes, I understand that the baseline of your question is the CMCD model. However, the public release of CMCD is not within the scope of our project, so we are not providing a clear public release. If you need any other assistance, please let us know.

**Comment by coding-dallas** [comment]
Would it be possible to share the model summary of the baseline and hypeparameter used in it...
